train:
    doc:
        null
    query:
        null
dev:
    doc: 
        init_args:
            _target_: modules.processors.multidomain_dataset_processor.TechQA_docs
            split: all
    query: 
        init_args:
            _target_: modules.processors.multidomain_dataset_processor.TechQA
            split: all
test:
    doc:
        null
    query:
        null