system: "Refer to the background document and answer the questions:\n\n"
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "You are a helpful assistant. Answer the questions as short as possible."
user_without_docs: "Question: {question}"