init_args: 
    _target_: models.generators.llm_cocom.LLMCocom
    model_name: "cocom"
    batch_size: 64
    checkpoint_path: "/scratch/1/user/mlouis/calmar/expcocom/unique_adapter_128/0ad95c551c7923fc/last_model"
    context_max_length: 512
    max_new_tokens: 128
    model_max_length: 1280
    compr_rate: null