init_args: 
  _target_: models.generators.llm.LLM
  model_name: "meta-llama/Llama-2-13b-chat-hf"
  max_new_tokens: 128
  max_length: 2048
  quantization: "int4"
  batch_size: 16
  attn_implementation: 'sdpa'


