generate_test_samples: 5
test_size_ratio: 0.01
trainer:
  dataloader_num_workers: 4
  eval_accumulation_steps: 16
  num_train_epochs: 2
  weight_decay: 0.1
  warmup_ratio: 0.05
  learning_rate: 1e-4
  gradient_accumulation_steps: 32
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  bf16: True
  report_to: "tensorboard"
  max_grad_norm: 1.