train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.MsMarcoCollection
            split: "full"

    query: 
        init_args:
            _target_: modules.dataset_processor.MsMarcoTrainQueries
            split: "full"
test:
    doc: null
    query: null
