train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.KILT100w
            split: "full"
    
    query: 
        init_args:
            _target_: modules.processors.qa_dataset_processor.POPQA
            split: "test"
test:
    doc: null
    query: null
