dev:
    doc:
        init_args:
            _target_: modules.processors.qa_dataset_processor.SCIQ
            split: "test"
    query:
        init_args:
            _target_: modules.processors.qa_dataset_processor.SCIQ
            split: "test"
