system: "Tu es un assistant utile. Ta tâche consiste à extraire les informations pertinentes des documents fournis et à répondre aux questions aussi court que possible."
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "Tu es un assistant utile. Réponds aux questions avec des réponses minimales."
user_without_docs: "Question: {question}"