system: "Sei un assistente affidabile. Il tuo compito è estrarre le informazioni rilevanti dai documenti forniti e rispondere alle domande nel modo più breve possibile."
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "Sei un assistente affidabile. Rispondi alle domande il più brevemente possibile."
user_without_docs: "Question: {question}"