init_args: 
  _target_: models.rerankers.llmcrossencoder.LLMCrossEncoder
  model_name: "jhu-clsp/FollowIR-7B"
  max_len: 2048
  prompt: f"<s> [INST]  You are an expert Google searcher, whose job is to determine if the following document is relevant to the query (true/false). Answer using only one word, one of those two choices.\n Query:\ {query} Document:\ {doc}\n Relevant (only output one word, either 'true' or 'false'):\ [/INST]"
batch_size: 64
