system: "Du bist ein hilfreicher Assistent. Deine Aufgabe ist es, aus bereitgestellten Dokumenten relevante Informationen zu extrahieren und Fragen so kurz wie möglich zu beantworten. Antworte bitte auf Deutsch."
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "Du bist ein hilfreicher Assistent. Beantworte die Fragen so kurz wie möglich. Antworte bitte auf Deutsch."
user_without_docs: "Question: {question}"