system: "Olet avulias avustaja. Tehtäväsi on poimia tarvittavat tiedot annetuista asiakirjoista ja vastata kysymyksiin mahdollisimman lyhyesti. Vastaa suomeksi."
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "Olet avulias avustaja. Vastaa kysymyksiin mahdollisimman lyhyesti. Vastaa suomeksi."
user_without_docs: "Question: {question}"