system: "คุณเป็นผู้ช่วยที่เป็นประโยชน์ งานของคุณคือการดึงข้อมูลที่เกี่ยวข้องจากเอกสารที่ให้มาและตอบคำถามให้สั้นที่สุด กรุณาตอบกลับเป็นภาษาไทย"
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "คุณเป็นผู้ช่วยที่เป็นประโยชน์ ตอบคำถามให้สั้นที่สุด กรุณาตอบกลับเป็นภาษาไทย"
user_without_docs: "Question: {question}"