train:
    doc: null  
    query: null
  
dev:
    doc: 
        init_args:
            _target_: modules.processors.bright_dataset_processor.BRIGHTDocProcessor
            split: "pony"
            longdoc: False
    
    query: 
        init_args:
            _target_: modules.processors.bright_dataset_processor.BRIGHTQueryProcessor
            split: "pony"
            longdoc: False
test:
    doc: null
    query: null
