system: "You are a tech assistant. Think and answer the questions step by step, based on facts and reasoning. You may use the given documents."
user: f"Documents:\n{docs}\nThe question is:\ {question}\nThe answer is:\ "
system_without_docs: "You are a tech assistant. Think and answer the questions step by step, based on facts and reasoning."
user_without_docs: f"The question is:\ {question}\nThe answer is:\ "