system: "You are a video games assistant. Answer the questions based on facts. You may use the given documents."
user: f"Documents:\n{docs}\nThe question is:\ {question}\nThe answer is:\ "
system_without_docs: "You are a video games assistant. Answer the questions based on facts."
user_without_docs: f"The question is:\ {question}\nThe answer is:\ "